

import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ashikulislam
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setSize(1366, 766);
    }

    public Home(String role) {
        initComponents();
        setLocationRelativeTo(null);
        if (role.equals("Admin")) {
            btnAdminPanel.setEnabled(false);

        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnAdminPanel = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnViewOrder = new javax.swing.JButton();
        btnStorage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogOut.setBackground(new java.awt.Color(204, 204, 255));
        btnLogOut.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit3.png"))); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setPreferredSize(new java.awt.Dimension(145, 46));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 630, -1, -1));

        btnAdminPanel.setBackground(new java.awt.Color(204, 204, 255));
        btnAdminPanel.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        btnAdminPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin1.png"))); // NOI18N
        btnAdminPanel.setText("Admin Panel");
        btnAdminPanel.setPreferredSize(new java.awt.Dimension(145, 46));
        btnAdminPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminPanelActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        btnCustomer.setBackground(new java.awt.Color(204, 204, 255));
        btnCustomer.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer2.png"))); // NOI18N
        btnCustomer.setText("Customer");
        btnCustomer.setMaximumSize(new java.awt.Dimension(137, 30));
        btnCustomer.setMinimumSize(new java.awt.Dimension(137, 30));
        btnCustomer.setPreferredSize(new java.awt.Dimension(145, 46));
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        btnOrder.setBackground(new java.awt.Color(204, 204, 255));
        btnOrder.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/orders1.png"))); // NOI18N
        btnOrder.setText("Order");
        btnOrder.setMaximumSize(new java.awt.Dimension(137, 30));
        btnOrder.setMinimumSize(new java.awt.Dimension(137, 30));
        btnOrder.setPreferredSize(new java.awt.Dimension(145, 46));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        btnViewOrder.setBackground(new java.awt.Color(204, 204, 255));
        btnViewOrder.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        btnViewOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewOrder1.png"))); // NOI18N
        btnViewOrder.setText("View Order");
        btnViewOrder.setMaximumSize(new java.awt.Dimension(137, 30));
        btnViewOrder.setMinimumSize(new java.awt.Dimension(137, 30));
        btnViewOrder.setPreferredSize(new java.awt.Dimension(145, 46));
        btnViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        btnStorage.setBackground(new java.awt.Color(204, 204, 255));
        btnStorage.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        btnStorage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/storage1.png"))); // NOI18N
        btnStorage.setText("Storage");
        btnStorage.setMaximumSize(new java.awt.Dimension(137, 30));
        btnStorage.setMinimumSize(new java.awt.Dimension(137, 30));
        btnStorage.setPreferredSize(new java.awt.Dimension(145, 46));
        btnStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStorageActionPerformed(evt);
            }
        });
        getContentPane().add(btnStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home_bg5.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:

      int choice = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

    if (choice == JOptionPane.YES_OPTION) {
        UserActivity activityManager = new UserActivity();
        activityManager.updateLogoutTime();  

        setVisible(false);  
        new login().setVisible(true); 
    } else {
        JOptionPane.showMessageDialog(null, "Logout cancelled. You are still logged in.");
    } 

    }//GEN-LAST:event_btnLogOutActionPerformed

    
    
    
    
    
    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
        // TODO add your handling code here:
        new ManageViewOrder().setVisible(true);


    }//GEN-LAST:event_btnViewOrderActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        new ManageOrder().setVisible(true);
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        new ManageCustomer().setVisible(true);

    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStorageActionPerformed
        // TODO add your handling code here:
        new ManageStorage().setVisible(true);


    }//GEN-LAST:event_btnStorageActionPerformed

    private void btnAdminPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminPanelActionPerformed
        // TODO add your handling code here:
        new ManageAdminPanel().setVisible(true);

    }//GEN-LAST:event_btnAdminPanelActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminPanel;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnStorage;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
